name: Artifacts Retention Policy

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    name: Clean up old images
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: misery7100
          package-name: xray-headless
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true
