name: Artifacts Retention Policy

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    name: Clean up old images
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          image-names: xray-headless
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-selection: untagged
          cut-off: 1h
