name: Artifacts Retention Policy

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    name: Clean up old images
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: xray-headless
          package-type: container
          ignore-versions: '^(latest|v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$)'
